### ISSUE TITLE
Rendering text labels when labels length exceeds the length of the line

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#13]
We are building tiles where the point size of line labels can exceed the width of the line. In these case, labels are applied very sparsely (see example tiles).

I don't have a complete example to share, since it would require access to our database, but let me know if you can't reproduce it. I can try to get something out of rundemo.py.

Please feel free to contact me if you need more information or testing.

**Comment by flippmoke** [comment]
Not sure if this is still an issue closing for now

**Comment by Andrey-VI** [comment]
Is this really has been fixed?

**Comment by springmeyer** [comment]
Right, not fixed and we should expose and option to do what QGIS allows. Thanks for the graphic @Andrey-VI.

**Comment by talaj** [comment]
I'm closing this as https://github.com/mapnik/mapnik/pull/3512 was merged.

**Comment by springmeyer** [comment]
Great, thank you @talaj!
