### ISSUE TITLE
Incorrect centroid calculation on polygon with interior rings

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2078]
Testcase: https://gist.github.com/springmeyer/7459651

The above testcase reads a single WKT multipolygon into a single path and the resulting centroid is incorrect:

![broken](https://f.cloud.github.com/assets/20300/1537770/e10e7162-4cce-11e3-84cd-824cf3e55995.png)

The same labeling happens if the data is read from WKB format/from PostGIS.

However, if the data is read from a shapefile labeling is correct:

![works](https://f.cloud.github.com/assets/20300/1537781/0f2175cc-4ccf-11e3-932e-cf594591ee93.png)

This is because `shape_io::read_polygon` interprets the inner rings/holes as individual parts and the default behavior of only labeling the largest works as expected.

This can be fixed for PostGIS with the below patch:

```diff
diff --git a/src/wkb.cpp b/src/wkb.cpp
index 65f6145..cc73243 100644
--- a/src/wkb.cpp
+++ b/src/wkb.cpp
@@ -345,9 +345,9 @@ private:
         int num_rings = read_integer();
         if (num_rings > 0)
         {
-            std::auto_ptr<geometry_type> poly(new geometry_type(Polygon));
             for (int i = 0; i < num_rings; ++i)
             {
+                std::auto_ptr<geometry_type> poly(new geometry_type(Polygon));
                 int num_points = read_integer();
                 if (num_points > 0)
                 {
@@ -360,9 +360,9 @@ private:
                     }
                     poly->close_path();
                 }
+                if (poly->size() > 3) // ignore if polygon has less than (3 + close_path) vertices
+                    paths.push_back(poly);
             }
-            if (poly->size() > 3) // ignore if polygon has less than (3 + close_path) vertices
-                paths.push_back(poly);
         }
     }
 
```

**Comment by artemp** [comment]
should be fixed in d682c5a2017b387d1391aee2a6afb9df801d9b3d

**Comment by springmeyer** [comment]
@artemp awesome, but looks like you missed adding `mapnik/geometry_centroid.hpp`?

**Comment by artemp** [comment]
@springmeyer - fixed in 8411cdfa0c0d62d3e0500394c4459764790077a8

**Comment by springmeyer** [comment]
great, closing, will by fixed by #2739.
