### ISSUE TITLE
C++ unit test crashes on windows

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2838]
`test.exe` does not run on windows:

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	test.exe
  Application Version:	0.0.0.0
  Application Timestamp:	555d0828
  Fault Module Name:	MSVCP140.dll
  Fault Module Version:	14.0.22129.1
  Fault Module Timestamp:	5428bf04
  Exception Code:	c0000005
  Exception Offset:	0000000000017151
  OS Version:	6.2.9200.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	a7ef
  Additional Information 2:	a7ef7ee9e61686e051cbdff2d4feddc8
  Additional Information 3:	6b68
  Additional Information 4:	6b68f2538afca9db14b39156c8920f04

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=190175

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

**Comment by BergWerkGIS** [comment]
Got by the `test.exe` compilation error (https://github.com/mapnik/node-mapnik/issues/446#issuecomment-104648171) via https://github.com/mapnik/mapnik-gyp/commit/d496090427f48830ffeeeb5ecb89337ff1ec9f1b

But several tests fail:

![image](https://cloud.githubusercontent.com/assets/4549888/7775673/79a12780-00b5-11e5-9fa8-a2aa94928341.png)

![image](https://cloud.githubusercontent.com/assets/4549888/7775677/801aa4ec-00b5-11e5-827a-1c696fc4bfe4.png)

![image](https://cloud.githubusercontent.com/assets/4549888/7775684/86197e68-00b5-11e5-8f2c-12c1e192152c.png)

![image](https://cloud.githubusercontent.com/assets/4549888/7775688/8d742eec-00b5-11e5-9250-b7a26e140830.png)

![image](https://cloud.githubusercontent.com/assets/4549888/7775696/93c3870c-00b5-11e5-991b-74982592defa.png)

**Comment by BergWerkGIS** [comment]
@springmeyer you were correct, there were some leftovers from a previous built.
Removed them and got by the above errors.

Debugging `test.exe` breaks here in `utils.hpp`:

![image](https://cloud.githubusercontent.com/assets/4549888/7784508/2d4ec956-0168-11e5-911e-dc356d079522.png)

**Comment by springmeyer** [comment]
can you try commenting that line and see if the test.exe is able to run of it is crashes elsewhere?

**Comment by BergWerkGIS** [comment]
Y, already doing this atm :smile:

**Comment by springmeyer** [comment]
dumping more brainstorming here. I think this problem is popping up now because of the change of moving many different tests into one exe. Various different tests call structures that are singletons (like `datasource_cache`). Maybe when the application initializes global variables there is undefined order and that is triggering boost to throw a lock error.

Hopefully just removing the lock will fix things. And according to the C++11 standard that may actually now be viable (http://stackoverflow.com/a/11711991/2333354).

If it is more complex I think most of the clues we may need to solve this are described or linked from http://stackoverflow.com/a/28050250/2333354. @BergWerkGIS do you know if we are using "CRT initialization"?

Other ideas to narrow/workaround we could try:

  - comment out all lines of `mapnik::datasource_cache::instance().register_datasource` in the `test/unit/*` files. This will cause test failures but maybe this will at least allow the `test.exe` to run without needing to modify `include/mapnik/utils.hpp`
  - or, another way of accomplishing the above would be to [try restricting the `text.exe`](https://github.com/mapnik/mapnik-gyp/blob/master/mapnik.gyp#L526) to build just one `cpp` like `test/unit/core/box2d_test.cpp`. I presume that would work. Then we could slowly add more `cpp` until we hit the problem. My guess is the problem will start once more than one file with `datasource_cache` is included:

```
$ grep register_datasource ./test/unit/ -r -I
./test/unit//core/copy_move_test.cpp:        mapnik::datasource_cache::instance().register_datasources("plugins/input/shape.input");
./test/unit//core/exceptions_test.cpp:            mapnik::datasource_cache::instance().register_datasource(csv_plugin);
./test/unit//core/exceptions_test.cpp:            mapnik::datasource_cache::instance().register_datasource(shape_plugin);
./test/unit//imaging/image_painted_test.cpp:        datasource_cache::instance().register_datasources("plugins/input/csv.input");
```

**Comment by springmeyer** [comment]
@BergWerkGIS - I think this might fix things: https://gist.github.com/springmeyer/363a04d61e9593048c63

**Comment by BergWerkGIS** [comment]
@springmeyer nope.
@flippmoke FYI

1.)
Directory structure is a bit different on Windows: no `plugins/input` folder:
![image](https://cloud.githubusercontent.com/assets/4549888/7864611/8f12ffbe-0563-11e5-9f38-2be9cfd15831.png)

2.)
I have yet to find the current working directory of the tests, as the relative path doesn't work.
When I specify the full path to the input plugins via `register_datasources` all tests are successful.

**Comment by BergWerkGIS** [comment]
Oh, I found `plugins/input`, but they only contain `obj`s and not the compiled binary:
![image](https://cloud.githubusercontent.com/assets/4549888/7864781/75884c56-0564-11e5-8aeb-fb6d26f5c4aa.png)

**Comment by BergWerkGIS** [comment]
@springmeyer @flippmoke 

Tests seem to work now.
I stepped through the tests in the debugger and these are my findings (running a clean build atm):

* I have to apply those patches: 
  * [remove lockguard](https://github.com/mapbox/windows-builds/blob/master/patches/mapnik-test.exe-crash-lock_guard.diff)
  * [paths for plugins](https://github.com/mapbox/windows-builds/blob/master/patches/mapnik-test.exe-crash.diff)
  * Although the second one might not be necessary anymore, because of the next two steps (not tested yet)
* `cd` into `mapnik` clone dir
* copy input plugins from `mapnik-gyp\build\lib\mapnik\input\*.input` to `plugins\input\`
* execute tests via `mapnik-gyp\build\test\test.exe`

**Comment by BergWerkGIS** [comment]
Yes, copying the plugins did the trick, everything ran through and all tests were successful.
Will verify during the next days if 2nd patch can be omitted.

**Comment by BergWerkGIS** [comment]
Verifed with VS2014CTP4 and VS2015RC1, that 

* commenting [`std::lock_guard<std::mutex> lock(mutex_);`](https://github.com/mapbox/windows-builds/blob/master/patches/mapnik-test.exe-crash-lock_guard.diff)
* copying `mapnik-gyp\build\lib\mapnik\input\*.input` into `plugins\input`

makes the tests succeed.

Adjusting paths like in @springmeyer 's [gist](https://gist.github.com/springmeyer/363a04d61e9593048c63) is **not** necessary.

**Comment by artemp** [comment]
@BergWerkGIS  - could you try latest master to verify this issue is fixed?

**Comment by springmeyer** [comment]
@artemp - I just tested and found that the same crash is still present. However, like before I can avoid the crash if I remove the lock at https://github.com/mapnik/mapnik/blob/master/include/mapnik/util/singleton.hpp#L109

**Comment by artemp** [comment]
@springmeyer - hmm..I'm starting to think VS 2014 CTP 4 is broken somehow or maybe our win build is missing some extra flags

**Comment by springmeyer** [comment]
I've been working on narrowing this down. It looks like the test crash only happens if I include the tests from `test/unit/imaging/*`. Next step is to narrow down further by selectively adding specific tests inside that folder to see which one starts the crash happening.

**Comment by springmeyer** [comment]
It is this line that triggers the crash: https://github.com/mapnik/mapnik/blob/master/test/unit/imaging/tiff_io.cpp#L11

**Comment by artemp** [comment]
Current design hides image readers implementations. Using .cpp through #include might end up creating duplicate symbols on windows or some other clashes .. a bit of a guessing here

**Comment by springmeyer** [comment]
Noticing that building tiff_io.cpp

```
CXX = '/opt/llvm/bin/clang++ -fsanitize=address -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/'
CC = '/opt/llvm/bin/clang -fsanitize=address'
CUSTOM_CXXFLAGS = '--coverage'
CUSTOM_LDFLAGS = '--coverage'
```

Is hanging clang on my machine:

```
$ /opt/llvm/bin/clang++ -v
clang version 3.8.0 (http://llvm.org/git/clang.git c64147ff0ff60667f106dd47dae789f417f941e8) (http://llvm.org/git/llvm.git 30709900f394ba33d546b6830eadc7307add3219)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
InstalledDir: /opt/llvm/bin

```
