### ISSUE TITLE
Build error: scons: *** Do not know how to make File target `plugins/input/geojson/geojson_datasource.os'

### ISSUE THREAD

**Issue by knutole** [mapnik/mapnik#3384]
Ubuntu 14.04. Trying to build latest master (7cd5301cbe85c8e254d253cc9b12037112419200).

```
In file included from include/mapnik/feature.hpp:29:0,
                 from src/agg/process_line_symbolizer.cpp:24:
include/mapnik/value.hpp:123:39: warning: shadowed declaration is here [-Wshadow]
 using value = value_adl_barrier::value;
                                       ^
src/agg/process_line_symbolizer.cpp: In instantiation of 'void mapnik::agg_renderer<T0, T1>::process(const mapnik::line_symbolizer&, mapnik::feature_impl&, const mapnik::proj_transform&) [with T0 = mapnik::image<mapnik::rgba8_t>; T1 = mapnik::label_collision_detector4]':
src/agg/process_line_symbolizer.cpp:237:68:   required from here
src/agg/process_line_symbolizer.cpp:192:57: warning: declaration of 'apply' shadows a member of 'this' [-Wshadow]
         apply_vertex_converter_type apply(converter, ras);
                                                         ^
src/agg/process_line_symbolizer.cpp:222:62: warning: declaration of 'apply' shadows a member of 'this' [-Wshadow]
         apply_vertex_converter_type apply(converter, *ras_ptr);
                                                              ^
scons: *** Do not know how to make File target `plugins/input/geojson/geojson_datasource.os' (/tmp/mapnik/plugins/input/geojson/geojson_datasource.os).  Stop.
scons: building terminated because of errors.
make: *** [src/json/libmapnik-json.a] Error 2
```

As a sidenote, would it be possible to add Ubuntu to Travis CI?

**Comment by lightmare** [comment]
There is Ubuntu Precise build on travis -- but with many upgraded packages that are even newer than Trusty's.

This is caused by optional sources in memory-intensive list
 - [ ] plugins/input/geojson/geojson_datasource.os
 - [ ] utils/mapnik-index/process_geojson_file.o

Just checked compiling with gcc 4.8 and these two need ~2GB memory.

**Comment by knutole** [comment]
Hum, I have 32GB ram on my build system. What can I do to build this?

I mentioned Travis CI because I've had issues building on Ubuntu 14.04
countless times. :/

On Thursday, 24 March 2016, lightmare <notifications@github.com> wrote:

> There is Ubuntu Precise build on travis -- but with many upgraded packages
> that are even newer than Trusty's.
>
> This is caused by optional sources in memory-intensive list
>
>    - plugins/input/geojson/geojson_datasource.os
>    - utils/mapnik-index/process_geojson_file.o
>
> Just checked compiling with gcc 4.8 and these two need ~2GB memory.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mapnik/mapnik/issues/3384#issuecomment-200986110>
>


-- 
Knut Ole Sjøli


*Systemapic.com <http://Systemapic.com>*
Oslo Science Park
Gaustadalléen 21
N-0349 Oslo, Norway

Tel: +47 4823 7873

**Comment by lightmare** [comment]
> Hum, I have 32GB ram on my build system. What can I do to build this?

Well then the easiest is probably edit Makefile and remove this dependency (it only serves to limit the total amount of memory needed by parallel compiles):
```diff
-mapnik: src/json/libmapnik-json.a
+mapnik:
```

**Comment by knutole** [comment]
Added patch above, now running into this:

```
In file included from utils/mapnik-index/process_geojson_file.cpp:37:0:
include/mapnik/json/extract_bounding_box_grammar_impl.hpp: In instantiation of 'mapnik::json::extract_bounding_box_grammar<Iterator, Boxes, ErrorHandler>::extract_bounding_box_grammar() [with Iterator = const char*; Boxes = std::vector<std::pair<mapnik::box2d<float>, std::pair<long unsigned int, long unsigned int> > >; ErrorHandler = mapnik::json::error_handler<const char*>]':
utils/mapnik-index/process_geojson_file.cpp:61:82:   required from here
include/mapnik/json/extract_bounding_box_grammar_impl.hpp:119:28: warning: suggest parentheses around comparison in operand of '|' [-Wparentheses]
                            |
                            ^
scons: building terminated because of errors.
make: *** [mapnik] Error 2
The command '/bin/sh -c sh /tmp/install-mapnik.sh /tmp/mapnik' returned a non-zero code: 1
```

**Comment by knutole** [comment]
`Boost: 1.54`  Should I upgrade? Thanks for your feedback!

**Comment by knutole** [comment]
Closing as the first build error was fixed with removing memory limits.

Created new ticket for second build error: https://github.com/mapnik/mapnik/issues/3385

**Comment by lightmare** [comment]
Reopening as the issue persists. Optional objects listed explicitly in Makefile: https://github.com/mapnik/mapnik/issues/3384#issuecomment-200986110

**Comment by dcdieci** [comment]
I just tried to install mapnik on ubuntu 14.04. and I do get the same error.

```
apt-get update
apt-get upgrade
git clone https://github.com/mapnik/mapnik --depth 10
cd mapnik
git submodule update --init deps/mapbox/variant
./configure
make && sudo make install

```
```
In file included from include/mapnik/feature.hpp:29:0,
                 from src/agg/process_line_symbolizer.cpp:24:
include/mapnik/value.hpp:123:39: warning: shadowed declaration is here [-Wshadow]
 using value = value_adl_barrier::value;
                                       ^
src/agg/process_line_symbolizer.cpp: In instantiation of 'void mapnik::agg_renderer<T0, T1>::process(const mapnik::line_symbolizer&, mapnik::feature_impl&, const mapnik::proj_transform&) [with T0 = mapnik::image<mapnik::rgba8_t>; T1 = mapnik::label_collision_detector4]':
src/agg/process_line_symbolizer.cpp:237:68:   required from here
src/agg/process_line_symbolizer.cpp:192:57: warning: declaration of 'apply' shadows a member of 'this' [-Wshadow]
         apply_vertex_converter_type apply(converter, ras);
                                                         ^
src/agg/process_line_symbolizer.cpp:222:62: warning: declaration of 'apply' shadows a member of 'this' [-Wshadow]
         apply_vertex_converter_type apply(converter, *ras_ptr);
                                                              ^
scons: *** Do not know how to make File target `plugins/input/geojson/geojson_datasource.os' (/home/phil/src/mapnik/plugins/input/geojson/geojson_datasource.os).  Stop.
scons: building terminated because of errors.
make: *** [src/json/libmapnik-json.a] Error 2
```

Very annoying since the installation as described in the wiki failed also on ubuntu 16.04.

**Comment by rinigus** [comment]
It looks like this error is preventing compilation of Mapnik in the systems with older Boost library. In particular, few checks are done on whether boost >= 1.56 and if its of a smaller version, some JSON plugins are not built. When using a system with older boost, its sufficient to remove mapnik dependency on libmapnik-json.a, as suggested above. But would be good to get this bug fixed to avoid the required patching.

**Comment by jeffbonhag** [comment]
Here is a workaround, rather than running `./configure` and Make targets (from 3385):

```python scons/scons.py configure
python scons/scons.py
python scons/scons.py install```
