### ISSUE TITLE
ShieldSymbolizer font size is incorrect for wide extents

### ISSUE THREAD

**Issue by shoeberto** [mapnik/mapnik#4067]
Hi all - I've run into an issue with newer versions of Mapnik that I haven't quite been able to figure out on my own, but I believe it may be a bug. We are just recently upgrading our app from 2.2.0 to 3.0.22 and have had issues with ShieldSymbolizers generating text with incorrectly sized fonts, for example:
![3 0 22_incorrect_shields svg](https://user-images.githubusercontent.com/7410361/59360898-ec90b880-8cfe-11e9-8fe3-c2286f6c2455.png)
This seems to happen when images have extents that are particularly wide. In this example image the extents are:
```
left=-8263373.9949741
right=-8199556.7200588
top=4987544.7594934
bottom=4953281.8615645
```
For comparison, the same request on 2.2.0 generates this:
![2 2 0_correct_shields svg](https://user-images.githubusercontent.com/7410361/59360896-ebf82200-8cfe-11e9-936c-a46c23757c65.png)

We did try to see if this is a recent issue, but compiling 3.0.18 also gave us the same issue:
![3 0 18_incorrect_shields svg](https://user-images.githubusercontent.com/7410361/59360897-ec90b880-8cfe-11e9-99ca-3a169ecc94e4.png)

Interestingly, this only seems to affect "wide" extents, as far as I can tell. For example, in 3.0.22, requesting a less wide image produces the output that I would expect:
![3 0 22_correct_shields svg](https://user-images.githubusercontent.com/7410361/59360900-ec90b880-8cfe-11e9-9381-cc6ed826568b.png)
These extents are:
```
left=-8244196.2766086
right=-8224046.8118901
top=4978536.7470961
bottom=4962958.6979593
```

We are just using the Python interface to access a database containing OSM street data. The Python code is a very simple CGI request handler:
```python3
    mapfile = f'layers/{layer}.xml'

    for required in ['left', 'right', 'top', 'bottom', 'width', 'height']:
        if required not in params:
            return error("Missing arguments")

    mapnik_map = mapnik.Map(int(params['width']), int(params['height']))

    mapnik.load_map(mapnik_map, mapfile)

    bbox = mapnik.Box2d(float(params['left']), float(params['bottom']), float(params['right']), float(params['top']))
    mapnik_map.zoom_to_box(bbox)

    header('image/svg+xml')
    sys.stdout.flush()

    surface = cairo.SVGSurface(sys.stdout.buffer, mapnik_map.width, mapnik_map.height)
    ctx = cairo.Context(surface)

    mapnik.render(mapnik_map, ctx)

    surface.finish()

```

Please let me know if I can provide any more information. I did try experimenting with `aspect_fix_mode` but it didn't seem to have any significant effect. I'm able to reproduce this fairly reliably in the USA regardless of where I'm looking.

**Comment by talaj** [comment]
Is there a chance Cairo or FreeType has been also upgraded with Mapnik? I'm recollecting that I had similar issues with some versions of these libraries. I think I've solved it by building against latest versions.

**Comment by shoeberto** [comment]
Thanks @talaj - It sounds as though FreeType was the newest version and was compiled from source along with Mapnik, but Cairo is using an older version (1.14.8) from the Amazon Linux 2 yum repo. As part of this migration, we are upgrading our Mapnik server from Amazon Linux to Amazon Linux 2, so there is certainly a big potential for change there.

Do you recall which library specifically might have been at fault, and which version of each seemed to resolve the issue?

**Comment by talaj** [comment]
> Do you recall which library specifically might have been at fault, and which version of each seemed to resolve the issue?

I'm successfully rendering PDF and SVG maps with Cairo 1.15.12 and FreeType 2.9.1. There were more issues I solved by upgrading these libraries, so I don't know which one actually fixed it.

But still, this can be different issue than I had. I don't want to mislead you. Updating those libraries is worth trying. If it wont help it would be great if you can make a test case I can run locally and do some debugging.

**Comment by shoeberto** [comment]
No worries, I understand that there may be another issue still - for now we will try using the library versions that you posted and see what happens. I'll report back once I find out more. Thank you!
